server:
  port: 9079
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true



spring:
  profiles:
    include: dev
  #Date类型反序列化为时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #springmvc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1
  application:
    name: transit-service
  main:
    allow-bean-definition-overriding: true
  messages:
    encoding: UTF-8
  codec:
    max-in-memory-size: 20MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    database:
      default: 2
      token: 2
      tenant: 2
      snowflake: 3
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 2
    jedis:
      pool:
        max-active: 8  #最大连接数
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 8 #最大空闲
    # SQL DAO Configuration
    jpa:
      repositories:
        enabled: "true"

